# Generated by Django 2.1.1 on 2018-11-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julius_app', '0002_auto_20181110_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeldetalhes',
            options={'verbose_name': 'ModeloDetalhes'},
        ),
        migrations.AlterModelOptions(
            name='modeleconomizou',
            options={'verbose_name': 'ModeloEconomizou'},
        ),
        migrations.AddField(
            model_name='modeleconomizou',
            name='descricao',
            field=models.TextField(default='', max_length=250, verbose_name='descricao'),
        ),
    ]
